//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDiscounts
    {
        public int OrderDiscountID { get; set; }
        public int OrderID { get; set; }
        public int CodeID { get; set; }
        public decimal DiscountAmount { get; set; }
    
        public virtual DiscountCodes DiscountCodes { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
