//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VoucherShopEntities : DbContext
    {
        public VoucherShopEntities()
            : base("name=VoucherShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppSettings> AppSettings { get; set; }
        public virtual DbSet<CustomerPreferences> CustomerPreferences { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<DiscountCodes> DiscountCodes { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<OrderDiscounts> OrderDiscounts { get; set; }
        public virtual DbSet<OrderItems> OrderItems { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<UserLoginHistory> UserLoginHistory { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VoucherCategories> VoucherCategories { get; set; }
        public virtual DbSet<VoucherHistory> VoucherHistory { get; set; }
        public virtual DbSet<VoucherReviews> VoucherReviews { get; set; }
        public virtual DbSet<Vouchers> Vouchers { get; set; }
    }
}
