//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherHistory
    {
        public int HistoryID { get; set; }
        public int VoucherID { get; set; }
        public string ChangeDescription { get; set; }
        public Nullable<System.DateTime> ChangedAt { get; set; }
        public int ChangedBy { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Vouchers Vouchers { get; set; }
    }
}
